export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const UPDATE_EMPLOYEE_FORM = 'UPDATE_EMPLOYEE_FORM';
export const CLEAR_EMPLOYEE_FORM = 'CLEAR_EMPLOYEE-FORM';
export const UPDATE_EMPLOYEE_LIST = 'UPDATE_EMPLOYEE_LIST';
